# Generated by Django 3.2.11 on 2022-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to='videos'),
            preserve_default=False,
        ),
    ]
