# Generated by Django 3.2.11 on 2022-05-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
