# Generated by Django 3.2.11 on 2022-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='video_comments', to='users.Comment'),
        ),
    ]
