# Generated by Django 3.2.11 on 2022-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pornstar'),
        ('videos', '0004_alter_video_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pornstars',
            field=models.ManyToManyField(blank=True, to='users.Pornstar'),
        ),
    ]
