# Generated by Django 4.0.4 on 2022-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_alter_comment_author'),
        ('videos', '0005_video_pornstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to='users.profile'),
        ),
    ]
