# Generated by Django 4.0.4 on 2022-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.FileField(null=True, upload_to='videos/previews'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
