# Generated by Django 4.0.4 on 2022-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_preview_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeQualityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='videos/alternatives')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='alternative_qualities',
            field=models.ManyToManyField(blank=True, to='videos.alternativequalityvideo'),
        ),
    ]
