# Generated by Django 4.0.4 on 2022-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alternativequalityvideo_video_alternative_qualities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='videos/previews'),
        ),
    ]
