# Generated by Django 4.0.4 on 2022-06-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_3d',
            field=models.BooleanField(default=False),
        ),
    ]
