# Generated by Django 4.1.2 on 2022-10-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_remove_subscription_profile"),
        ("users", "0003_profile_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="subscriptions.subscription",
            ),
        ),
    ]
