# Generated by Django 4.1.2 on 2022-10-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_alter_comment_author"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="user",),
        migrations.AddField(
            model_name="subscription",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
