# Generated by Django 4.1.2 on 2022-10-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_remove_subscription_user_subscription_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="profile",),
    ]
